### ISSUE TITLE
TypeError: assessment_prompt() missing 1 required positional argument: 'language' Traceback: File "/app/chergpt-starter-kit/main.py", line 518, in main     assessment_prompt(

### ISSUE THREAD

**Issue by lookang** [String-sg/ai-starter-kit#32]
for version 20231018
seems like line 518 is missing the language argument?

TypeError: assessment_prompt() missing 1 required positional argument: 'language'
Traceback:
File "/app/chergpt-starter-kit/main.py", line 518, in main
    assessment_prompt(
<img width="1391" alt="Screenshot 2023-10-18 at 8 55 23 AM" src="https://github.com/String-sg/chergpt-starter-kit/assets/20143558/a0e9521a-9c47-48f0-ac66-ac0e2c90e6ec">

**Comment by twahidin** [comment]
resolved, I output out the language from record_myself function as a variable and return it back to the assessment prompt function
