### ISSUE TITLE
bug: declaration is not enforced 

### ISSUE THREAD

**Issue by ghostleek** [String-sg/ai-starter-kit#46]
<img width="1305" alt="image" src="https://github.com/String-sg/chergpt-starter-kit/assets/44336310/46b2f79d-853d-4152-b283-e629f4c4f821">

fix:
(1) to prevent action until acknowledgement of this note is done
(2 UX / copywriting of this

**Comment by twahidin** [comment]
Not a bug, the Super Administrator is the one who can use the application without the acknowledgment. Users who are Administrator and below will need to acknowledge before they can use. 

![image](https://github.com/String-sg/ai-starter-kit/assets/64293979/ef67720f-fa82-4759-8cfb-09e8e8e6ebed)
