### ISSUE TITLE
bug/ AttributeError: module 'streamlit_antd_components' has no attribute 'chip'

### ISSUE THREAD

**Issue by ghostleek** [String-sg/ai-starter-kit#47]
<img width="1248" alt="image" src="https://github.com/String-sg/chergpt-starter-kit/assets/44336310/9b7a3275-9b21-4036-9606-7be2a6071df0">

To reproduce: click on tab under Ai Chatbot

**Comment by twahidin** [comment]
Issue with chip will be solved when it is upgraded to streamlit-antd-components==0.2.4
